# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='img',
            field=models.CharField(default='', max_length=100),
        ),
    ]
