# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 04:49
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_section_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='img',
            field=models.ImageField(upload_to=blog.models.post_dir_path),
        ),
    ]
