# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20160226_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='title_url',
            field=models.URLField(default='#'),
        ),
    ]
